##############################
##############################
## Coveralls GitHub Actions ##
##############################
##############################

name: Coverage

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

###########################################
# Start the job on all push/pull requests #
###########################################
on: [push, pull_request]

###############
# Set the Job #
###############
jobs:
  test:
    # Name the Job
    name: Test coverage
    
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
    
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      ############################
      # Setup python environment #
      ############################
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: |
          pip install -r requirements.txt
          pip install coverage

      ################
      # Run coverage #
      ################
      - name: Run coverage
        run: coverage run -m unittest discover -b -s tests

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
